apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2023-09-01T13:06:12Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v2.autoscaling
  uid: 080025cc-32c2-44f9-af64-abab95e20882
spec:
  group: autoscaling
  groupPriorityMinimum: 17500
  version: v2
  versionPriority: 30
status:
  conditions:
  - lastTransitionTime: "2023-09-01T13:06:12Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
