apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2024-01-02T05:31:55Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  name: v1beta1.metallb.io
  uid: 7392c78f-218f-46f9-b3d5-e26fa1922991
spec:
  group: metallb.io
  groupPriorityMinimum: 1000
  version: v1beta1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2024-01-02T05:31:55Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
