apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2023-09-01T13:06:12Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.discovery.k8s.io
  uid: 6be36faf-6003-42b0-b37b-54af87f1e6ad
spec:
  group: discovery.k8s.io
  groupPriorityMinimum: 16200
  version: v1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2023-09-01T13:06:12Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
