apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2024-01-02T05:31:55Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  name: v1alpha1.metallb.io
  uid: 186ce174-e725-49c3-846f-36bb580ed462
spec:
  group: metallb.io
  groupPriorityMinimum: 1000
  version: v1alpha1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2024-01-02T05:31:55Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
