apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2023-09-01T13:06:12Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.events.k8s.io
  uid: afdfeda7-c42d-4d0a-bf87-2c16cbda9d71
spec:
  group: events.k8s.io
  groupPriorityMinimum: 17750
  version: v1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2023-09-01T13:06:12Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
