apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-09-01T13:06:13Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:pv-protection-controller
  uid: 198c1aa8-7e40-4c77-88e1-3d43a3fd28bd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:pv-protection-controller
subjects:
- kind: ServiceAccount
  name: pv-protection-controller
  namespace: kube-system
