apiVersion: crd.projectcalico.org/v1
kind: ClusterInformation
metadata:
  annotations:
    projectcalico.org/metadata: '{"uid":"12e8fdd8-f43d-45e7-9693-7e37590e56fd","creationTimestamp":"2023-12-27T18:11:11Z"}'
  creationTimestamp: "2023-12-27T18:11:11Z"
  name: default
  uid: 12e8fdd8-f43d-45e7-9693-7e37590e56fd
spec:
  calicoVersion: v3.26.1
  clusterGUID: 1b8e01f7cb314df3b249d4421f8e6776
  clusterType: k8s,kdd,bgp,kubeadm
  datastoreReady: true
