apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"labels":{"app":"katafygio","chart":"katafygio-0.5.1","heritage":"Helm","release":"katafygio"},"name":"katafygio"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"katafygio"},"subjects":[{"kind":"ServiceAccount","name":"katafygio","namespace":"default"}]}
  creationTimestamp: "2024-01-08T11:19:32Z"
  labels:
    app: katafygio
    chart: katafygio-0.5.1
    heritage: Helm
    release: katafygio
  name: katafygio
  uid: ba7ee2ba-b9d2-4b89-be03-1a36aaf5fd7e
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: katafygio
subjects:
- kind: ServiceAccount
  name: katafygio
  namespace: default
