apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-09-01T13:06:13Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:replication-controller
  uid: b980f721-728c-4d71-bae8-309079c97fdd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:replication-controller
subjects:
- kind: ServiceAccount
  name: replication-controller
  namespace: kube-system
