apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-09-01T13:06:13Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:clusterrole-aggregation-controller
  uid: 0cd7c285-e7b2-46fc-aadb-dbe9970a7a59
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:clusterrole-aggregation-controller
subjects:
- kind: ServiceAccount
  name: clusterrole-aggregation-controller
  namespace: kube-system
