apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"kube-rbac-proxy","app.kubernetes.io/created-by":"urlcontroller","app.kubernetes.io/instance":"proxy-rolebinding","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"clusterrolebinding","app.kubernetes.io/part-of":"urlcontroller"},"name":"urlcontroller-proxy-rolebinding"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"urlcontroller-proxy-role"},"subjects":[{"kind":"ServiceAccount","name":"urlcontroller-controller-manager","namespace":"urlcontroller-system"}]}
  creationTimestamp: "2023-10-11T06:22:25Z"
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: urlcontroller
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: urlcontroller
  name: urlcontroller-proxy-rolebinding
  uid: 46ca5f3c-6cbe-4a96-aca4-f4edc523c5a8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: urlcontroller-proxy-role
subjects:
- kind: ServiceAccount
  name: urlcontroller-controller-manager
  namespace: urlcontroller-system
