apiVersion: flowcontrol.apiserver.k8s.io/v1beta2
kind: FlowSchema
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2023-09-01T13:06:12Z"
  name: kube-scheduler
  uid: 7e8dd357-4dbe-483a-8389-8d550b4c445c
spec:
  distinguisherMethod:
    type: ByNamespace
  matchingPrecedence: 800
  priorityLevelConfiguration:
    name: workload-high
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    resourceRules:
    - apiGroups:
      - '*'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
    - kind: User
      user:
        name: system:kube-scheduler
status:
  conditions:
  - lastTransitionTime: "2023-09-01T13:06:12Z"
    message: This FlowSchema references the PriorityLevelConfiguration object named
      "workload-high" and it exists
    reason: Found
    status: "False"
    type: Dangling
