apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-25T06:32:38Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{cert-manager-controller}
  kind: Pod
  name: cert-manager-7476c8fcf4-fzmh5
  namespace: cert-manager
  resourceVersion: "1608659"
  uid: 8f6e0df1-1bad-4c54-9494-7ac25a20a5b6
kind: Event
lastTimestamp: "2024-01-25T06:32:38Z"
message: Container image "quay.io/jetstack/cert-manager-controller:v1.12.0" already
  present on machine
metadata:
  creationTimestamp: "2024-01-25T06:32:38Z"
  name: cert-manager-7476c8fcf4-fzmh5.17ad8371aa7873f6
  namespace: cert-manager
  uid: d89ee1a7-e18b-4a39-831b-cc7d358550b8
reason: Pulled
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Normal
