apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-25T06:32:36Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: cert-manager-webhook-5655dcfb4b-w5mn2
  namespace: cert-manager
  resourceVersion: "1608665"
  uid: ddcad1b0-18e1-484a-bedb-cf9abdfc5b90
kind: Event
lastTimestamp: "2024-01-25T06:32:36Z"
message: Pod sandbox changed, it will be killed and re-created.
metadata:
  creationTimestamp: "2024-01-25T06:32:38Z"
  name: cert-manager-webhook-5655dcfb4b-w5mn2.17ad837134c53266
  namespace: cert-manager
  uid: 1c8652da-0e3f-4afe-8740-5f58e5007235
reason: SandboxChanged
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Normal
