apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app":"webhook","app.kubernetes.io/component":"webhook","app.kubernetes.io/instance":"cert-manager","app.kubernetes.io/name":"webhook","app.kubernetes.io/version":"v1.12.0"},"name":"cert-manager-webhook:dynamic-serving","namespace":"cert-manager"},"rules":[{"apiGroups":[""],"resourceNames":["cert-manager-webhook-ca"],"resources":["secrets"],"verbs":["get","list","watch","update"]},{"apiGroups":[""],"resources":["secrets"],"verbs":["create"]}]}
  creationTimestamp: "2024-01-02T05:31:33Z"
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: webhook
    app.kubernetes.io/version: v1.12.0
  name: cert-manager-webhook:dynamic-serving
  namespace: cert-manager
  uid: db9e9605-5152-4f0d-acaa-71533e7a3205
rules:
- apiGroups:
  - ""
  resourceNames:
  - cert-manager-webhook-ca
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
