apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-25T06:33:08Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{controller}
  kind: Pod
  name: controller-595f88d88f-vzh8v
  namespace: metallb-system
  resourceVersion: "1608589"
  uid: ba0eb06a-abf9-4545-b945-8959f7317a30
kind: Event
lastTimestamp: "2024-01-25T06:33:08Z"
message: Container controller failed liveness probe, will be restarted
metadata:
  creationTimestamp: "2024-01-25T06:33:08Z"
  name: controller-595f88d88f-vzh8v.17ad8378da762ed2
  namespace: metallb-system
  uid: b2cf338a-7202-4d1e-af6f-1c0159b0c0ff
reason: Killing
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Normal
