apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/port: "7472"
    prometheus.io/scrape: "true"
  creationTimestamp: "2024-01-02T05:31:56Z"
  generateName: speaker-
  labels:
    app: metallb
    component: speaker
    controller-revision-hash: bfc8bd5d8
    pod-template-generation: "1"
  name: speaker-rp4dd
  namespace: metallb-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: speaker
    uid: 9043d607-180c-4efe-ab92-edbc9973eb6a
  uid: 76c502b4-4bfc-4838-aa8a-35cff23c33e5
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - minikube
  containers:
  - args:
    - --port=7472
    - --log-level=info
    env:
    - name: METALLB_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: METALLB_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: METALLB_ML_BIND_ADDR
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: METALLB_ML_LABELS
      value: app=metallb,component=speaker
    - name: METALLB_ML_SECRET_KEY_PATH
      value: /etc/ml_secret_key
    image: quay.io/metallb/speaker:v0.13.10
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: monitoring
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: speaker
    ports:
    - containerPort: 7472
      hostPort: 7472
      name: monitoring
      protocol: TCP
    - containerPort: 7946
      hostPort: 7946
      name: memberlist-tcp
      protocol: TCP
    - containerPort: 7946
      hostPort: 7946
      name: memberlist-udp
      protocol: UDP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: monitoring
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_RAW
        drop:
        - ALL
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/ml_secret_key
      name: memberlist
      readOnly: true
    - mountPath: /etc/metallb
      name: metallb-excludel2
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bk5wr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: minikube
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: speaker
  serviceAccountName: speaker
  terminationGracePeriodSeconds: 2
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - name: memberlist
    secret:
      defaultMode: 420
      secretName: memberlist
  - configMap:
      defaultMode: 256
      name: metallb-excludel2
    name: metallb-excludel2
  - name: kube-api-access-bk5wr
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-02T05:31:56Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-25T06:33:39Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-25T06:33:39Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-02T05:31:56Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://bc7ea0c3754c0b2bc241232430e55bcd6e0659cd5fb6f6df83984a62bb5c47ab
    image: quay.io/metallb/speaker:v0.13.10
    imageID: docker-pullable://quay.io/metallb/speaker@sha256:00406ccb1fa08d48cc0ed0b43db7b3cbc3ccc1c4da0e38fca648e64639b06c3c
    lastState:
      terminated:
        containerID: docker://3aea93dfd9264bae6bd7b0933a838e0cdbf3e7c1cf5420bf9b0cf7cc14468fab
        exitCode: 1
        finishedAt: "2024-01-25T06:33:08Z"
        reason: Error
        startedAt: "2024-01-25T06:32:37Z"
    name: speaker
    ready: true
    restartCount: 16
    started: true
    state:
      running:
        startedAt: "2024-01-25T06:33:23Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 192.168.49.2
  podIPs:
  - ip: 192.168.49.2
  qosClass: BestEffort
  startTime: "2024-01-02T05:31:56Z"
