apiVersion: v1
data:
  secretkey: Yk9UTzZXaFJZSTFURG4zT3dRKzBjdw==
kind: Secret
metadata:
  creationTimestamp: "2024-01-02T05:32:21Z"
  name: memberlist
  namespace: metallb-system
  ownerReferences:
  - apiVersion: apps/v1
    kind: Deployment
    name: controller
    uid: 5ce4e214-26b0-42d3-8be0-b128248b3b34
  uid: d1e4b276-f47a-458d-87b1-71a8a04001be
type: Opaque
