apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"metallb"},"name":"speaker","namespace":"metallb-system"}}
  creationTimestamp: "2024-01-02T05:31:56Z"
  labels:
    app: metallb
  name: speaker
  namespace: metallb-system
  uid: 49464e58-e681-4219-a0d0-6ae8170ce725
