apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"go-app","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"go-app"}},"template":{"metadata":{"labels":{"app":"go-app"}},"spec":{"containers":[{"image":"sharmag07/url-short:a2","name":"go-app","ports":[{"containerPort":8090}],"resources":{"limits":{"cpu":"800m","memory":"128Mi"}}}]}}}}
  creationTimestamp: "2023-10-31T07:09:41Z"
  name: go-app
  namespace: default
  uid: e4f66a27-c56d-431d-a506-d920c0587721
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: go-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
    spec:
      containers:
      - image: sharmag07/url-short:a2
        imagePullPolicy: IfNotPresent
        name: go-app
        ports:
        - containerPort: 8090
          protocol: TCP
        resources:
          limits:
            cpu: 800m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-10-31T07:09:41Z"
    lastUpdateTime: "2023-11-02T06:50:25Z"
    message: ReplicaSet "go-app-697df4b455" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-01-25T06:30:45Z"
    lastUpdateTime: "2024-01-25T06:30:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
