apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-25T06:32:36Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: niginx
  namespace: default
  resourceVersion: "1608643"
  uid: dc7bc6c4-ab93-41e3-8e16-6c57c985f904
kind: Event
lastTimestamp: "2024-01-25T06:32:36Z"
message: Pod sandbox changed, it will be killed and re-created.
metadata:
  creationTimestamp: "2024-01-25T06:32:38Z"
  name: niginx.17ad83713462a6dc
  namespace: default
  uid: e411ddb6-f62c-4c37-a38b-396e6486d3d5
reason: SandboxChanged
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Normal
