apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-25T06:32:43Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{katafygio}
  kind: Pod
  name: katafygio-88f5d8f5f-4pwh5
  namespace: default
  resourceVersion: "1608657"
  uid: 277abf8b-b990-46fc-bd66-30e0c27d8eca
kind: Event
lastTimestamp: "2024-01-25T06:32:43Z"
message: Created container katafygio
metadata:
  creationTimestamp: "2024-01-25T06:32:43Z"
  name: katafygio-88f5d8f5f-4pwh5.17ad8372ef2d3665
  namespace: default
  uid: 010491d9-5777-42de-91f3-fbcbc9dad776
reason: Created
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Normal
