apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-11-07T08:38:19Z"
  labels:
    deleteLock: enabled
  name: niginx
  namespace: default
  uid: dc7bc6c4-ab93-41e3-8e16-6c57c985f904
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: niginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tjflm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-tjflm
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-11-07T08:38:19Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-25T06:32:42Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-25T06:32:42Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-11-07T08:38:19Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://3788e83bbe982a55c511cbb995881d9cbf7b27dbbd19947cf99a656d2d02c6ae
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
    lastState:
      terminated:
        containerID: docker://0191abf12864eaa9edf3986f4ad62007b2fb4cc7a3c07b29da70e9cf7329049a
        exitCode: 0
        finishedAt: "2024-01-25T06:31:57Z"
        reason: Completed
        startedAt: "2024-01-25T06:27:14Z"
    name: niginx
    ready: true
    restartCount: 12
    started: true
    state:
      running:
        startedAt: "2024-01-25T06:32:41Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 10.244.0.244
  podIPs:
  - ip: 10.244.0.244
  qosClass: BestEffort
  startTime: "2023-11-07T08:38:19Z"
