apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"go-app-svc","namespace":"default"},"spec":{"ports":[{"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"go-app"},"type":"NodePort"}}
  creationTimestamp: "2023-10-31T07:09:41Z"
  name: go-app-svc
  namespace: default
  uid: 1a3cda5e-b411-4e9c-bedd-87d8af51a9ea
spec:
  clusterIP: 10.109.54.81
  clusterIPs:
  - 10.109.54.81
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30176
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
