apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-09-01T13:06:13Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  uid: fe254319-9d8f-4a69-9a63-89a058bb4d1a
spec:
  clusterIP: 10.96.0.1
  clusterIPs:
  - 10.96.0.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
