apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: kube-backups
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-10-26T04:58:03Z"
  labels:
    app: katafygio
    app.kubernetes.io/managed-by: Helm
    chart: katafygio-0.5.1
    heritage: Helm
    release: kube-backups
  name: kube-backups-katafygio
  namespace: default
  uid: 76178c42-90ba-4c7d-90f4-2ecb9d779259
