apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"k8s-delete-validation-webhook","namespace":"default"},"spec":{"ports":[{"port":443,"targetPort":443}],"selector":{"app":"k8s-delete-validation-webhook"}}}
  creationTimestamp: "2023-11-07T08:36:13Z"
  name: k8s-delete-validation-webhook
  namespace: default
  uid: a4c9d7f5-b2c9-41eb-9d2d-f5971eaa6a8e
spec:
  clusterIP: 10.110.216.226
  clusterIPs:
  - 10.110.216.226
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: k8s-delete-validation-webhook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
