apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-25T06:32:45Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{calico-node}
  kind: Pod
  name: calico-node-tdncx
  namespace: kube-system
  resourceVersion: "1608636"
  uid: 5f40c6a5-9fb4-4214-ace2-2e8e84832da4
kind: Event
lastTimestamp: "2024-01-25T06:32:45Z"
message: |
  Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
  W0125 06:32:45.526648     209 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
metadata:
  creationTimestamp: "2024-01-25T06:32:45Z"
  name: calico-node-tdncx.17ad837368015e3c
  namespace: kube-system
  uid: 6068da9d-5ed1-414f-822c-72543a0a56bf
reason: Unhealthy
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Warning
