apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-25T06:32:31Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{kube-scheduler}
  kind: Pod
  name: kube-scheduler-minikube
  namespace: kube-system
  uid: eb675835e10503c79265cf0e2983f93c
kind: Event
lastTimestamp: "2024-01-25T06:32:31Z"
message: Started container kube-scheduler
metadata:
  creationTimestamp: "2024-01-25T06:32:38Z"
  name: kube-scheduler-minikube.17ad837036cabfe5
  namespace: kube-system
  uid: 957b1280-ed61-4844-b391-76665989d8ae
reason: Started
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Normal
