apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-25T06:32:38Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{coredns}
  kind: Pod
  name: coredns-5d78c9869d-tm77f
  namespace: kube-system
  resourceVersion: "1608641"
  uid: 55e0e3c9-3c23-4b06-a46b-25d269e9736c
kind: Event
lastTimestamp: "2024-01-25T06:32:38Z"
message: Container image "registry.k8s.io/coredns/coredns:v1.10.1" already present
  on machine
metadata:
  creationTimestamp: "2024-01-25T06:32:38Z"
  name: coredns-5d78c9869d-tm77f.17ad8371b4b7daf2
  namespace: kube-system
  uid: c5e67bf1-87e2-4625-89a4-6407e3b11cf2
reason: Pulled
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Normal
