apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-25T06:32:31Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{kube-controller-manager}
  kind: Pod
  name: kube-controller-manager-minikube
  namespace: kube-system
  uid: b3702ceb912504d37098b922ccdcfa41
kind: Event
lastTimestamp: "2024-01-25T06:32:31Z"
message: Created container kube-controller-manager
metadata:
  creationTimestamp: "2024-01-25T06:32:38Z"
  name: kube-controller-manager-minikube.17ad83702c97fede
  namespace: kube-system
  uid: 56e9f022-ba6b-4a5c-a448-07f2600d172c
reason: Created
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Normal
