apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-25T06:32:37Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.initContainers{upgrade-ipam}
  kind: Pod
  name: calico-node-tdncx
  namespace: kube-system
  resourceVersion: "1608636"
  uid: 5f40c6a5-9fb4-4214-ace2-2e8e84832da4
kind: Event
lastTimestamp: "2024-01-25T06:32:37Z"
message: Started container upgrade-ipam
metadata:
  creationTimestamp: "2024-01-25T06:32:38Z"
  name: calico-node-tdncx.17ad83719e34bc39
  namespace: kube-system
  uid: 3d82f6f0-c30c-4231-8ff6-b719684a8f93
reason: Started
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Normal
