apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-25T06:32:38Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{kube-proxy}
  kind: Pod
  name: kube-proxy-ffgxk
  namespace: kube-system
  resourceVersion: "1608647"
  uid: 70b17335-bdf5-41fd-aa8f-9ac210c05a1c
kind: Event
lastTimestamp: "2024-01-25T06:32:38Z"
message: Started container kube-proxy
metadata:
  creationTimestamp: "2024-01-25T06:32:38Z"
  name: kube-proxy-ffgxk.17ad8371a9df0d21
  namespace: kube-system
  uid: d428ee33-c4bf-49f6-9f66-1db863a0d8d6
reason: Started
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Normal
