apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-09-01T13:06:13Z"
  name: kubeadm:nodes-kubeadm-config
  namespace: kube-system
  uid: a1305194-7082-4fe4-a43f-1582a39b4a4a
rules:
- apiGroups:
  - ""
  resourceNames:
  - kubeadm-config
  resources:
  - configmaps
  verbs:
  - get
