apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"calico-cni-plugin","namespace":"kube-system"}}
  creationTimestamp: "2023-12-27T18:10:35Z"
  name: calico-cni-plugin
  namespace: kube-system
  uid: d305f1ad-da82-4f67-bcd9-f9e2a4b973f6
